name: Run Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: DUB Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest, dmd-beta, ldc-latest, ldc-beta]
        exclude:
          - { os: macOS-latest, dc: dmd-latest }
          - { os: macOS-latest, dc: dmd-beta }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run Unittests
        run: dub -q test
